import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from 'next/headers';
import { redirect } from 'next/navigation';
import Navbar from '@/components/Navbar';
import jwt from 'jsonwebtoken';
import redis from '@/lib/redis';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ekhoes",
  description: "Generated by create next app",
};

const COOKIE_NAME = process.env.COOKIE_NAME;
const JWT_SECRET = process.env.JWT_SECRET;

const noNavBar = ['/login'];


/**
 * Check tolen validity and related session on Redis
 * @param {string} token 
 */
async function isAuthenticated(token) {

    try {
      const decoded = jwt.verify(token, JWT_SECRET);
      const session = await redis.get(decoded.sessionId);

      if (session) {
        const data = JSON.parse(session);

		/*
        // Renew session
        data.updated = new Date().toISOString();
        data.path = url;
        await redis.set(decoded.sessionId, JSON.stringify(data));
		*/
        return true;

      } else {
        console.log('[layout] Session not found:', decoded.sessionId);
      }
    } catch (e) {
      console.log('[layout] Token error:', e.message);
    }

    return false;
}

export default async function RootLayout({ children }) {
  const allHeaders = await headers();
  const url = allHeaders.get('x-url');
  const hideNavbar = noNavBar.includes(url);

  const cookieStore = await cookies();
  const token = cookieStore.get(COOKIE_NAME)?.value || '';

  if (token) {
    if (!await isAuthenticated(token)) {
      console.log('[layout] Token found. Session not found');
      redirect('/logout');
    }
  }

  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative h-screen bg-black text-white overflow-hidden">
          {/* Sfondo */}
          <div className="absolute inset-0 z-0">
            <img
              src="/digital-echo.jpg"
              alt="digital echo background"
              className="w-full h-full object-cover blur-sm brightness-20"
            />
          </div>

          {/* Overlay */}
          <div className="absolute inset-0 bg-[#00f2ff]/10 z-10 mix-blend-multiply"></div>

          {/* ✅ Navbar + contenuto con z-index più alto */}
          <div className="relative z-20">
            {!hideNavbar && <Navbar />}
            {children}
          </div>
        </div>



      </body>
    </html>
  );
}
