import { Geist, Geist_Mono } from "next/font/google";
import { headers } from 'next/headers';
import Navbar from '@/components/Navbar';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ekhoes",
  description: "Generated by create next app",
};

const noNavBar = ['/login', '/sign-in'];

export default async function RootLayout({ children }) {
  const allHeaders = await headers();
  const url = allHeaders.get('x-url');
  const hideNavbar = noNavBar.includes(url);

  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative h-screen bg-black text-white overflow-hidden">
          {/* Sfondo */}
          <div className="absolute inset-0 z-0">
            <img
              src="/digital-echo.jpg"
              alt="digital echo background"
              className="w-full h-full object-cover blur-sm brightness-20"
            />
          </div>

          {/* Overlay */}
          <div className="absolute inset-0 bg-[#00f2ff]/10 z-10 mix-blend-multiply"></div>

          {/* ✅ Navbar + contenuto con z-index più alto */}
          <div className="relative z-20">
            {!hideNavbar && <Navbar />}
            {children}
          </div>
        </div>



      </body>
    </html>
  );
}
